{% set name = "rat" %}
{% set version = "3.0.0.alpha.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# source:
#   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rat-{{ version }}.tar.gz
#   sha256: b3a5045caa0a80ee4b01765350d049bfd6e3f2d63a02893df76aa4b342f00cf2
# source:
#   git_url: https://github.com/UW-SASWE/RAT.git
#   git_branch: sm-main-pypi
source:
  path: ./src
  folder: /cheetah1/sanchit_global_rat/rat_build

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - rat = rat.cli.rat_cli:main

requirements:
  host:
    - git
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - xarray =2022.3.0
    - geopandas
    - rasterio
    - rioxarray
    - earthengine-api
    - pyyaml
    - ruamel_yaml
    - netcdf4
    - dask

test:
  requires:
    - pytest

about:
  home: https://pypi.org/project/rat/
  summary: Resevoir Monitoring using Satellite Remote Sensing
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Pritam28877
