{% set name = "rat" %}
{% set version = "3.0.0.alpha.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/UW-SASWE/RAT.git
  git_tag: main
  git_depth: 1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 4
  entry_points:
    - rat = rat.cli.rat_cli:main

requirements:
  host:
    - git
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - xarray =2022.3.0
    - geopandas
    - rasterio
    - rioxarray
    - earthengine-api
    - pyyaml
    - ruamel_yaml
    - netcdf4
    - dask

test:
  requires:
    - pytest

about:
  home: https://pypi.org/project/rat/
  summary: Resevoir Monitoring using Satellite Remote Sensing
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Pritam28877
