{% set name = "rat" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rat-{{ version }}.tar.gz
  sha256: b3a5045caa0a80ee4b01765350d049bfd6e3f2d63a02893df76aa4b342f00cf2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

about:
  home: https://pypi.org/project/rat/
  summary: Resevoir Monitoring using Satellite Remote Sensing
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Pritam28877
