site_name: RAT
site_description: Reservoir Assessment Tool 3.0
site_author: Sanchit Minocha | UW SASWE 
repo_url: https://github.com/UW-SASWE/RAT
site_url: https://rat-satellitedams.readthedocs.io/
theme:
    name: readthedocs
    logo: logos/rat_logo_white_icon.png
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    include_homepage_in_sidebar: false
    features:
      - content.code.copy  
    icon:
      admonition:
        success: fontawesome/solid/check
        warning: fontawesome/solid/triangle-exclamation
copyright: Written and maintained by <a href="https://www.linkedin.com/in/sanchitminochaiitr/">Sanchit Minocha</a> <br> Copyright &copy; 2023, <a href="https://saswe.net/">University of Washington SASWE Research Group</a> 
docs_dir: docs
site_dir: site
use_directory_urls: true
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

plugins:
    - markdownextradata
nav:
# Main pages
- Home:
    - 'RAT': 'index.md'
- Quick Start: 
    - 'User Guide': 'QuickStart/UserGuide.md'
- RAT Configuration:
    - 'Configuration File': 'Configuration/rat_config.md'
    - 'Secrets File': 'Configuration/secrets.md'
- Development:
    - 'Development Guide': 'Development/DevelopmentGuide.md'    


extra_css: [css/extra.css]
extra:
  homepage: https://depts.washington.edu/saswe/rat/
  rat_version:
    major: 3
    minor: 0