MetSim:
    # Time step in minutes
    time_step: 360
    # Forcings begin here (year-month-day)
    start: 2001-4-1
    # Forcings end at this date (year-month-day)
    stop: 2021-6-10
    # Input and output directories
    forcing: '/houston2/pritam/rat_mekong_v3/backend/data/metsim_inputs/forcings_all.nc'
    domain: '/houston2/pritam/rat_mekong_v3/backend/params/metsim/domain.nc'
    state: '/houston2/pritam/rat_mekong_v3/backend/params/metsim/state.nc'
    forcing_fmt: 'netcdf'
    in_format: 'netcdf'
    out_dir: '/houston2/pritam/rat_mekong_v3/backend/data/metsim_results_conf'
    out_prefix: '6H_VIC'
#     out_prefix: 'yaml_output'
#     prec_type: 'triangle'
#     utc_offset: True
    calendar: 'proleptic_gregorian'
    # time_grouper: 'Y'

out_vars:
    temp:
        out_name: 'temp'
    prec:
        out_name: 'prec'
    shortwave:
        out_name: 'shortwave'
    longwave:
        out_name: 'longwave'
    air_pressure:
        out_name: 'air_pressure'
    vapor_pressure:
        out_name: 'vapor_pressure'
    wind:
        out_name: 'wind'

chunks:
    lat: 30
    lon: 20

forcing_vars:
    # Format is metsim_name: input_name
    prec  : 'precip'
    t_max : 'tmax'
    t_min : 'tmin'
    wind  : 'wind'

state_vars:
    # Format is metsim_name: input_name
    prec  : 'precip'
    t_max : 'tmax'
    t_min : 'tmin'
    wind  : 'wind'

domain_vars:
    # Format is metsim_name: input_name
    lat  : 'lat'
    lon  : 'lon'
    mask : 'mask'
    elev : 'elev'
