{% set name = "rat" %}
{% set version = "3.0.0a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 134c12f003f817b32a48a2f598d39b630eecd970a7152b530f60a0869a7e62d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - rat = rat.cli.rat_cli:main

requirements:
  host:
    - git
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - xarray =2022.3.0
    - geopandas
    - rasterio
    - rioxarray
    - earthengine-api
    - pyyaml
    - ruamel_yaml
    - netcdf4
    - dask
    - requests

test:
  requires:
    - pytest

about:
  home: https://pypi.org/project/rat/
  summary: Resevoir Monitoring using Satellite Remote Sensing
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Pritam28877
