name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          auto-update-conda: true
          channels: conda-forge,defaults
          environment-file: environment.yml
      - name: Install test modules
        shell: bash -l {0}
        run: |
          conda info
          conda install mamba -y
          mamba install pytest conda-build -y
      - name: Build RAT
        shell: bash -l {0}
        run: |
          conda develop src/
      - name: Test RAT
        shell: bash -l {0}
        run: |
          conda activate test
          pytest
